name: Deploy Frontend to EC2 Production

on:
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for frontend
      run: |
        docker build -t kamartinez/my-react-app .

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/my-react-app

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 44.208.233.5
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop my-react-app || true
          docker rm my-react-app || true

          docker pull kamartinez/my-react-app

          docker run -d --name my-react-app -p 80:80 --restart unless-stopped kamartinez/my-react-app
